app: tiny-site 
listen: ":8080"
redis: 127.0.0.1:6379
track: jt
# 用于内部生成图片接口的校验，长度10到30
# adminToken: abcd
session:
  # 默认为以下值，可不配置
  # cookie:
  #   name: jt
  #   maxAge: 24h
  #   path: /
  expires: 24h
  # 此keys用于cookie的合法校验，请在正式环境中，另外生成此keys并保密
  keys:
    - cuttlefish
    - tree.xie
locationByIP: http://ip.taobao.com/service/getIpInfo.php
db:
  uri: postgres://tree:mypwd@127.0.0.1:5432/tiny-site?connect_timeout=5&sslmode=disable
  poolSize: 100
upload:
  # 临时缓存文件的大小
  cacheSize: 1024
tiny:
  address: 127.0.0.1:3016
  # GUETZLI的处理时间特别慢，此超时还需要根据需要调整
  timeout: 10s
  maxWidth: 2048
  maxHeight: 2048
  maxQuality: 100
  maxFileSize: 1449616
  # 生成的图片地址前缀，可以指定为CDN再回源
  # imageURLPrefix: http://oidm8hv4x.qnssl.com